# Inventory file for Ansible
# Collection of all hosts
[all:children]
proxmox_hosts

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
ansible_user=user
ansible_become=yes
ansible_become_method=sudo
wazuh_manager_ip=wazuh.angry.fish

# Proxmox hosts
[proxmox_hosts]
10.11.0.11 # pve01
10.11.0.12 # pve02
10.11.0.13 # pve03
10.11.0.31 # pbs01
10.11.0.101 # new pve01
10.11.0.102 # new pve02
10.11.0.103 # new pve03