---
- name: Configure Base System
  hosts: all
  become: true
  roles:
    - common

- name: Configure Wazuh Agents
  hosts: service_wazuh
  become: true
  roles:
    - wazuh_agent

- name: Setup Komodo Manager
  hosts: komodo_all
  roles:
    - docker
    - komodo

- name: Setup usbip
  hosts: usbip_host
  roles:
    - usb_ip_server

- name: Setup mini PCs
  hosts: mini_pc
  roles:
    - mini_pc

- name: Setup MinIO for Terraform state
  hosts: minio_hosts
  become: true
  roles:
    - docker
    - minio

- name: Setup NFS-Ganesha gateway
  hosts: nfs_gateway
  become: true
  roles:
    - nfs_gateway
    - pbs_backup

- name: Setup DMZ PC
  hosts: dmz_pc
  become: true
  roles:
    - docker
    - npm

- name: Setup Home Assistant host (Zigbee USB/IP attach)
  hosts: home_assistant
  become: true
  roles:
    - homeassistant