---
- name: Configure Base System
  hosts: all
  become: true
  roles:
    - common
    - wazuh_agent

- name: Unattended-upgrades
  hosts: unattended
  become: true
  roles:
    - unattended

- name: Setup Komodo Manager
  hosts: komodo_all
  roles:
    - docker
    - komodo

- name: Setup usbip
  hosts: usbip_host
  roles:
    - usb_ip