---
- name: Get list of snapshots for each VM
  shell: |
    /usr/sbin/qm listsnapshot {{ item }} | awk '/ansible_backup_/ {print $2}' | sort
  loop: "{{ backup_vm_ids | unique }}"
  register: snapshot_list
  failed_when: false
  changed_when: false

- name: Delete old snapshots (keep only the last one)
  shell: |
    echo "{{ item.stdout_lines[:-1] | join(' ') }}" | xargs -n1 -r -I{} /usr/sbin/qm delsnapshot {{ item.item }} {}
  loop: "{{ snapshot_list.results }}"
  when:
    - item.stdout_lines is defined
    - item.stdout_lines | length > 1
  register: delete_result
  failed_when: false
  changed_when: item.stdout_lines | length > 1