---
- name: Update Apt
  apt:
    update_cache: yes

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: Reload UFW
  community.general.ufw:
    state: reloaded