---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: [update, always]

- name: Install common packages
  apt:
    name:
      - python3
      - htop
      - git
      - curl
      - ufw
      - fail2ban
      - unattended-upgrades
      - apt-listchanges
    state: present
  tags: [setup, packages]

- name: Enable unattended-upgrades
  ansible.builtin.debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: "true"
    vtype: boolean

- name: Setup unattended-upgrades config
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: '0644'
  notify: Restart unattended-upgrades

- name: Upgrade all packages
  apt:
    upgrade: dist
    force_apt_get: yes
  tags: [update]

- name: Remove unused packages
  apt:
    autoremove: yes
    autoclean: yes
  tags: [update]

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required
  tags: [update]

- name: Notify if reboot is needed
  debug:
    msg: "⚠️  Reboot is required on {{ inventory_hostname }}"
  when: reboot_required.stat.exists
  tags: [update]

- name: Install Chrony (NTP)
  apt:
    name: chrony
    state: present
  tags: [ntp, setup]

- name: Configure NTP Server
  lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: '^pool '
    line: "pool 0.no.pool.ntp.org iburst"
    backup: yes
  notify: Restart Chrony
  tags: [ntp, setup]

- name: Ensure Chrony is enabled and running
  service:
    name: chrony
    state: started
    enabled: yes
  tags: [ntp, setup]

- name: Set system timezone to Europe/Oslo
  community.general.timezone:
    name: Europe/Oslo
  become: true

- name: Create fail2ban jail.local for SSH
  copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 1h
      findtime = 10m
      maxretry = 5
      
      [sshd]
      enabled = true
      port = 22
      logpath = %(sshd_log)s
      backend = %(sshd_backend)s
    mode: '0644'
  notify: Restart Fail2Ban


- name: Allow Common Ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  loop: "{{ common_ports }}"

- name: Ensure Fail2Ban is running
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Enable UFW Firewall
  community.general.ufw:
    state: enabled