# Copy this file to vault.yml and encrypt it with ansible-vault.
VELOX_PASSWORD: REPLACE_ME
MYSQL_ROOT_PASSWORD: REPLACE_ME
MYSQL_PASSWORD: REPLACE_ME
MINIO_ROOT_PASSWORD: REPLACE_ME
WAZUH_INDEXER_PASSWORD: REPLACE_ME
WAZUH_MANAGER_PASSWORD: REPLACE_ME
GRAYLOG_PASSWORD: REPLACE_ME
SHUFFLER_API_KEY: REPLACE_ME
SHUFFLE_WORKFLOW_ID: REPLACE_ME
VELOCIRAPTOR_API_KEY_PATH: REPLACE_ME
SUBLIME_API_KEY: REPLACE_ME
INFLUXDB_API_KEY: REPLACE_ME
GRAFANA_PASSWORD: REPLACE_ME
VIRUSTOTAL_API_KEY: REPLACE_ME
PORTAINER_PASSWORD: REPLACE_ME
OPENAI_API_KEY: REPLACE_ME
OPENAI_MODEL: gpt-4o
OPENSEARCH_PASSWORD: REPLACE_ME
MCP_OPENSEARCH_AUTH_TOKEN: REPLACE_ME
MCP_MYSQL_AUTH_TOKEN: REPLACE_ME
WAZUH_PROD_PASSWORD: REPLACE_ME
komodo_passkey: REPLACE_ME
